# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5298cb4d8c8b35f7a38b985b75d10ef2357cad84dbdc2a1316388ce8ac9d2c62f1d8924bc46ebb707506f0062480385e508dff0d3af1af9040f55a9fc54414f4

test:
  secret_key_base: 22a731c22c1884e83f54b40efdf234b5aba6d730c01b9f7d78041c9334379de51f826070fceea000345a4703047fb07b401f51ef6fc9a00ec92cbc4be902c3f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
